# Generated by Django 3.0.5 on 2020-04-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200405_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qustion',
            new_name='question',
        ),
    ]
