# Generated by Django 3.0.5 on 2020-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20200406_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
