# Generated by Django 3.0.4 on 2020-03-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20200330_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='group',
        ),
        migrations.AlterField(
            model_name='helper',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
