# Generated by Django 3.0.4 on 2020-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20200330_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='helper_img'),
        ),
    ]
