# Generated by Django 3.0.4 on 2020-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_helper_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='profile_visible',
            field=models.BooleanField(null=True),
        ),
    ]
