# Generated by Django 3.0.4 on 2020-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20200330_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='cnic',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='helper',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
