# Generated by Django 3.0.4 on 2020-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_helper_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
