# Generated by Django 3.0.4 on 2020-03-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_auto_20200331_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.Area'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.City'),
        ),
    ]
