# Generated by Django 3.0.4 on 2020-03-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_auto_20200331_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
