# Generated by Django 3.0.4 on 2020-03-31 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0011_auto_20200331_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.Province'),
        ),
    ]
