# Generated by Django 3.0.4 on 2020-04-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0014_auto_20200402_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helper',
            old_name='Category',
            new_name='category',
        ),
    ]
