# Generated by Django 3.0.5 on 2020-04-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0016_auto_20200402_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/def_img.png', null=True, upload_to='helper_img'),
        ),
    ]
